- hosts: centos:new
  roles:
  - { role: geerlingguy.ntp }
#  gather_facts: no
  vars:
  - ntp_timezone: America/New_York    
  tasks:
  - name: Install yum
    yum: pkg=ntp state=present
  - name: Enable and restart NTP
    service: name=ntpd state=restarted enabled=yes
