- hosts: new
  user: root
  tasks:
  - name: reboot 
    command: shutdown -r now "Ansible updates triggered"
    async: 0
    poll: 0
    ignore_errors: true
  - name: waiting for server to come back
    local_action: wait_for host={{ inventory_hostname }}
                  state=started
    sudo: false
